### ISSUE TITLE
Error in until control (simple typo issue)

### ISSUE THREAD

**Issue by sromano** [dritchie/probabilistic-js#9]
You have a typo in *until* function which will cause it to call global *condition* function instead of actually calling the condition passed through the parameter to the *until* function.

https://github.com/dritchie/probabilistic-js/blob/master/probabilistic/control.js#L12
See **condiiton** vs **condition**

```
function until(condiiton, block)
{
	var cond = condition()
	while (!cond)
	{
		block()
		cond = condition()
	}
}
```

**Comment by longouyang** [comment]
Fixed in a865226e380a32bb1fea5a56c9ad2d75370e62f6

Thanks!
